language: node_js
matrix:
  fast_finish: true
node_js:
- '14'
branches:
  only:
  - master
  # tags
  - /^\d+\.\d+\.\d+(\-beta.\d+)?$/
env:
  global:
    - MATTERMOST_CHANNEL='{"dev":"feat---password-mgr","beta":"feat---password-mgr,publication","stable":"feat---password-mgr,publication"}'
    # GITHUB_TOKEN for yarn deploy script
    - secure: "mcBVV56jVLzyeJQ3xH32I3QCPLw1dfcP1DVi4hDQtiB9hzvy/qYFTE22q+uo+3R42KQ/kzw5NgPmecHTLpEcaYtSMe8Pgpfckioh8OeISXL7y7Vq5TdfdzfNL1B5zsI3/v6Li3YVxxNdosTzqVz1sJKkKJLFN2wXPNBGtLEpn5hZrv4zB3HvVLt5mhy6+KVuZAn6TrB2xsCfOy6G6+ySpwkbTop/YYkpgj/vfS9YOHcbsRTylHu+phvojASyl3tGRdfAREAv8f28ejBg5MwTkfeusl0a3DsowLIQdxZDuTIbw1cRW4MBx1jVDrfYQ0KocZClPKbfX9/+VNETl8nL5XKq7fDbeqRJ3QmFo1bNkPd9C9+Hw5nQ84XkrygwIK/lXEUTXjW+V608KPk8yVNWiSJ4vwGX2ovxYhvLwCnwoSbxQ2blhWBQseQh6lUwFZ3QL208z3g/VVgXvJmvNE1PCqwVEJwxYIgMr5hul8LSwM9thZo/3vryb/odk9LkHf1TA72LHBrQELdHb3/sJwEZt3bNtyvampRWdM2tc1EI2UAaUJlYzWekYYC7Iz9oMIyXpVJo4sWGCZ8oD39LnVlhYnnQ6F1LFOUswkU1RZhKWMFHsXTeQvSJmXFD1IVk9c0/r45V1SQmYtuCvMEk7kSrpOOOJPOL6DbItzUi0VVRY28="
    # REGISTRY_TOKEN for yarn cozyPublish script
    - secure: "wMOM7oD/Q//k8dho5K/dn+BagOeCMXm/60XJ+Gb07C4w6ynuQgiuANPM6f5eguflodTUX0Sv5D7x+y8+bITPc1aI7QbVDWphJa7UrCfNKgkTvU39jWDFkG1ZdYom6cngoosZ18ndVJ/L6K7YpM0FvmIl9tGneXIWbZoy2rBeoqMff1Ispc34TcKEvMyKyNgxaVb32vcp4nwDzwrHjjWAhSElfUCk5SAqb7ThtTGgWwWAfxhuQ1WxVI2QmM1fabuYaT5eXwrMlS9XG67QXwRash+9MG554J3CM0vG6RIVc2ThJp/ptaR9ASlimYSn29+E5EiAEAJdF9JQD07OKW2E2+UD8M9QWzQhp3x6kGj1YZY68DEBvQGcBFvoyW+0wPdTUbJXiFpy0hmiFxeV5F3Dux00y2Hi7arPq5ma+eh5oLwE+Z1QlBswMth57yiRtMJCv9EY0xmOveNpHmaUz9paXgZU5u9r2imubkVtUCCXd5iBwNX20MU0q5frGKLDeG+nVBJ6+g84nia3KgSG9tV+xRjSvsBpB6tUPbLzjNQTcyvqIIHv6chW5/9dVPxfk3grfOjpzh6mdd/F3qIP1cqOXqq118KJmRteZLmbharGqVbKbwZpA9pjf8JsuONvSmZm7LIoVwoGGKggWi5uybysH/IkMtho1m7qQfAdkI2f/mI="
    # MATTERMOST_HOOK_URL for yarn cozyPublish script
    - secure: "eHY0FQI3/rY1Q1gQkcNmLJo/LK0IyPyNrcVqbtYbMP7MmHBXAYh10JmKW2A8DbHmIE364J4kkCMYRICpn4lxXcTe2p3zBYy03q4bzwoKUpyTxUI0zjOeHQnGb1AsiP8mO3kAgontXbCl0X29AhmaQotK6jrQV+2ZEQ6jtyqe/ByZGPlsE1xVhOJgbREM2nSAidP3OcBzW7tsEeIciPYqoB9LsiSfzNM5nkfUodxO36gkh05tP3gE6Y8zP4HsbnUUHGafjpLLhRviIrK/DB8aDUzbxHRK7/g2D0FYsM8HYYfO3i/Agegt5/ImY2KM+K0mrn5UVDqFfhkSVjBetdiZCxSzC4rx+ljr9Kxp0deu/02ckapRj9x6PPLTs3BPWZT/h7IxTNYnpOpCIipHRtgyLjqH1ycvrHc+y7h5vOzX6hM/sF14LFp2RWddhQgr+iCXSIg6jK0OVPGdt57pum+hnZH2Yl96oSd8+YJG51KduOYau2iXrTtYu8XoYEdijxyMfzf6hueop/ymsr+3unbRzfrBrOkaYz2Yn+H8thY7VY1ofJoL2Ebmt8kIeRBx6sYcuVvfqOIxJItJxYegUGDFmIq02SMftOhT19MkzMJatVYPuwzP7RhKMkCy+0LCTNxP7RZ0W9Zgo7SRMF+cihkzn0SgtE/oLro/e/DNYsAG/gg="
cache:
  yarn: true
  directories:
  - node_modules
script:
  - npm run lint
  - npm run build:browser:prod
before_install:
  - sudo apt-get install libsecret-1-dev
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then openssl aes-256-cbc -K $encrypted_95a52b3b9b3c_key -iv $encrypted_95a52b3b9b3c_iv -in id_rsa_downcloud_cozy_pass_web.enc -out id_rsa_downcloud_cozy_pass_web -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then eval "$(ssh-agent -s)"; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then chmod 600 id_rsa_downcloud_cozy_pass_web; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then ssh-add id_rsa_downcloud_cozy_pass_web; fi 
before_deploy:
  - yarn add cozy-app-publish
deploy:
  - provider: script
    skip_cleanup: true
    # deploy the build on downcloud and publish to the Cozy registry
    script: yarn cozyPublish
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    # publish stable or beta versions using Github Releases (git tag)
    script: yarn cozyPublish
    on:
      tags: true